import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Vitals",
};

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-[var(--text)] mb-2">Terms of Service</h1>
      <p className="text-sm text-[var(--text-muted)] mb-10">Last updated September 12, 2026</p>

      <div className="space-y-8 text-[var(--text)] leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold mb-2">What Vitals is</h2>
          <p className="text-sm">
            Vitals is a financial health scoring and budgeting tool. It is not a bank, not a
            registered investment advisor, and not a licensed financial planning service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Not financial advice</h2>
          <p className="text-sm">
            Your score, narrative, and chat responses are provided for informational and
            educational purposes only. They are not a substitute for advice from a qualified
            financial professional. Before making significant financial decisions, we recommend
            consulting one.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">AI-generated content</h2>
          <p className="text-sm">
            Narrative summaries and chat responses are generated by AI models based on the
            numbers you provide. They can be incomplete, out of date, or simply wrong. Use your
            own judgment, and verify anything important before acting on it.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Account tiers</h2>
          <p className="text-sm">
            Vitals can be used without an account (Guest), with a free account (Free), or with a
            paid account (Pro). Feature availability and storage differ by tier, as described in
            the app.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Your responsibilities</h2>
          <p className="text-sm">
            Don&apos;t attempt to access another user&apos;s account or data, don&apos;t misuse
            the service to violate any law, and don&apos;t attempt to disrupt or reverse-engineer
            the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Ending your account</h2>
          <p className="text-sm">
            You may delete your account at any time from Settings, with immediate effect. We may
            suspend or terminate accounts found to be misusing the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Limitation of liability</h2>
          <p className="text-sm">
            Vitals is provided &quot;as is,&quot; without warranties of any kind. We are not
            liable for financial decisions made using information from the app, or for losses
            arising from its use.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Changes to these terms</h2>
          <p className="text-sm">
            If these terms change, we&apos;ll update the date at the top of this page.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Governing law</h2>
          <p className="text-sm">
            These terms are governed by the laws of the State of Texas, United States, without
            regard to its conflict-of-law principles.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">Contact</h2>
          <p className="text-sm">
            Questions about these terms? Reach out at{" "}
            <a href="mailto:pavanhebli@gmail.com" className="text-[var(--brand)] hover:underline">
              pavanhebli@gmail.com
            </a>
            .
          </p>
        </section>
      </div>

      <Link href="/" className="inline-block mt-10 text-sm text-[var(--brand)] hover:underline">
        ← Back to Vitals
      </Link>
    </div>
  );
}
